### ISSUE TITLE
Healing and Mana crystals should show 'mana gained' or some such, else players may not konw what is going on

### ISSUE THREAD

**Issue by Xillith** [talonos2/CurseIGMC#145]

**Comment by talonos2** [comment]
Is this from personal experience? Everybody, _including_ my father, whom I've seen playtest has gotten it intuitively.

**Comment by talonos2** [comment]
If we _do_ do this, I vote we use gab text, and we should have a global switch so that it only happens the first time.

**Comment by Xillith** [comment]
Fair enough. I had one person not get it. I also think it's intuitive personally. I would vote let's not spend the effort on it.

**Comment by Xillith** [comment]
Closing issue as only one person didn't get it, and not worth the time.
