### ISSUE TITLE
Having an elemental damage trinket equipped causes every attack using that element to say 'effective'

### ISSUE THREAD

**Issue by Xillith** [talonos2/CurseIGMC#152]

**Comment by talonos2** [comment]
LOLOL I know why that is. :(

**Comment by Xillith** [comment]
This may not be worth fixing to be honest.

**Comment by talonos2** [comment]
I'll be working on it on my laptop while other people playtest tomorrow.

**Comment by talonos2** [comment]
Unless we find any more _pressing_ bugs.
