### ISSUE TITLE
The player should (usually) glow.

### ISSUE THREAD

**Issue by talonos2** [talonos2/CurseIGMC#37]

**Comment by Xillith** [comment]
Ironically when you killed my versions to the common events it killed the player glowing also. :-p I'll add it back in upon my next push. Are you doing common event stuff right now? (I want to wait until common events are synced)

**Comment by talonos2** [comment]
No, I'm off for a while.

**Comment by Xillith** [comment]
Player has a glow while in dungeon like they should.
