### ISSUE TITLE
When gaining a new tier of crystals GUI shows undefined rather than the next exp bar

### ISSUE THREAD

**Issue by Xillith** [talonos2/CurseIGMC#44]

**Comment by Xillith** [comment]
Seems to only happen to red bar. Green bar just upgraded just fine

**Comment by Xillith** [comment]
Didn't happen second time I tested it... not sure what's going on there

**Comment by talonos2** [comment]
Pretty sure there's one monster somewhere that has it set to increase your red buff by some amount instead of your red crystals by some amount. If you manually mess with the buff amount, it messes up the GUI script.

**Comment by Xillith** [comment]
I'll go through the first few floors and check the monsters then. If I find one that did that I'll change it and mark this as resolved. (If I don't find something we'll have to keep this open for now)

**Comment by talonos2** [comment]
Has this happened recently?
