### ISSUE TITLE
Monsters will sometimes not die when killed, creating a loop of 5-10 battles against the same monster

### ISSUE THREAD

**Issue by Xillith** [talonos2/CurseIGMC#54]
Has happened with orcs and ghosts so far. Once that move randomly it seems?

**Comment by talonos2** [comment]
But not spiders?

**Comment by Xillith** [comment]
I havn't been on those levels lately, but it probably does affect them too. Also affects people that charge you. (Just happened). Not every fight does this happen, just sometimes.

**Comment by Xillith** [comment]
Never mind. I may of found it. Some monsters are not triggering the correct 'switch' to turn off. 

I'll see if I can fix any I run into

**Comment by talonos2** [comment]
This is why we want so badly to have testing time. Thanks, Xillith!

(There probably _used_ to be those sorts of errors with the spiders, but I've been testing those areas like mad.)

**Comment by Xillith** [comment]
Yeah. I fixed the 3 I ran into so far. I'll keep doing my lighting (which makes me walk around each map anyway) and fix these as they come. Should we close this ticket or let it run?

**Comment by talonos2** [comment]
Tickets are for tasks that people can pick up and work on if they're not sure what to do next.

We might make a ticket later for "fight every battle to make sure it dies correctly," but let's wait on such a ticket until mid next week.
