### ISSUE TITLE
Running out of time mid fight doesn't kill you and removes the timer. 

### ISSUE THREAD

**Issue by Xillith** [talonos2/CurseIGMC#60]

**Comment by Xillith** [comment]
Tested 10 times against a monster, and I can't replicate the issue. I'm not sure what we should do about this one as if it does happen it's game breaking (though not game crashing).

**Comment by talonos2** [comment]
Yeah, I was surprised when this went up on the issue tracker. I think a change I made to the SRD timer script recently may have accidentally solved it.

Let's keep an eye out for it.

**Comment by talonos2** [comment]
Has this happened recently?
