### ISSUE TITLE
Town is suspiciously large

### ISSUE THREAD

**Issue by talonos2** [talonos2/CurseIGMC#70]

**Comment by Ipecacuanha** [comment]
There is dialogue about people evacuating. It makes sense that there are houses boarded up. There also are events that happen at all edges of the map, and makes it so it takes a few turns before you see everything. adds exploration to those who are interested in it.

**Comment by talonos2** [comment]
Tonight, let's make sure to talk about possible ways to solve this issue while keeping the benefits listed above intact.
