### ISSUE TITLE
resting tutorial dialog happens before you go to floor 2

### ISSUE THREAD

**Issue by Ipecacuanha** [talonos2/CurseIGMC#87]
I preferred when the dialog happened as I entered the second floor, before going up against the bugs. 
It happened at the top of the stairs and got me impatient to see the next floor, so I clicked through instead of reading text.

**Comment by talonos2** [comment]
I'll fix it, but know this: The spiders start at the top side of the room, and the longer you wait, the more spiders are between you and the south side of the room.

I might make it so on the first run through, there are two fewer spiders in that room to compensate.
